POST 35.246.237.92:8080/api/v0/get-dictionary-from-src

body: {
src: string
}

res: {
data: {
src: string,
dictionary: [<entry>],
}
error: null/string
meta: {
languages: enum(string)
}
}

entry: {
dictionaryWord: string,
partOfSpeechTag: enum(string),
entriesInSrc: [{start: number, end: number}]
}


POST 35.246.237.92:8080/api/v0/add-known-word

body: {
dictionaryWord: string,
partOfSpeechTag: enum(string),
source: enum(string)
}